# Site settings
title: A Developer's Journey
email: jdrago.999@gmail.com
description: "Codifying intent.  Maintaining agility.  Scaling."
baseurl: ""
url: "https://jdrago999.github.io"
twitter_username: devstack
#github_username:  jdrago999
#facebook_username:  IronSummitMedia

highlighter: rouge

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]